# Generated by Django 3.2.4 on 2021-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Lastname',
            field=models.CharField(default=123, max_length=120),
            preserve_default=False,
        ),
    ]
