# Generated by Django 3.2.5 on 2021-07-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
